apiVersion: v1
kind: Service
metadata:
  name: jenkins-balancer
  labels:

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: jenkins
