kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: my-local-storage
  resources:
    requests:
      storage: 5Gi
